# Generated by Django 5.2.10 on 2026-02-01 04:49

import app.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-play-circle', max_length=50)),
                ('motion_file', models.CharField(blank=True, help_text='Path to motion template video', max_length=255)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=app.utils.Utils.generate_uuid, max_length=100, unique=True)),
                ('session_key', models.CharField(blank=True, help_text='For anonymous users', max_length=100)),
                ('input_image', models.ImageField(upload_to='animations/inputs/%Y/%m/')),
                ('input_image_url', models.URLField(blank=True)),
                ('output_format', models.CharField(choices=[('gif', 'GIF'), ('mp4', 'MP4'), ('webm', 'WebM')], default='gif', max_length=10)),
                ('duration', models.FloatField(default=3.0, help_text='Animation duration in seconds')),
                ('fps', models.IntegerField(default=24)),
                ('loop', models.BooleanField(default=True)),
                ('add_watermark', models.BooleanField(default=True)),
                ('output_file', models.FileField(blank=True, upload_to='animations/outputs/%Y/%m/')),
                ('output_url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='animations/thumbnails/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage 0-100')),
                ('error_message', models.TextField(blank=True)),
                ('job_id', models.CharField(blank=True, help_text='Background job ID', max_length=100)),
                ('api_request_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('preset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animator.animationpreset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animator.animation')),
            ],
            options={
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-is_featured', 'sort_order', '-created_at'],
            },
        ),
    ]
